# Generated by Django 4.2.2 on 2023-06-21 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year_published', models.PositiveIntegerField()),
                ('number_of_pages', models.PositiveIntegerField()),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Scifi'), ('Horror', 'Horror'), ('Other', 'Other')], max_length=255)),
                ('cover_photo', models.ImageField(upload_to='cover_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedicated_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ComicShop.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ComicInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComicShop.shoppingcart')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComicShop.comic')),
            ],
        ),
    ]
